### PR TITLE
Remove EJS

### PR DESCRIPTION
**Pull request by kvyuaiss**
https://github.com/carbonappio/Discord-Webhook-Proxy.git

### CODE REVIEW

**Comment by kvyuaiss** [comment]
@Sam512 You went across your own beliefs.

**Comment by realgavinmartin** [comment]
Looked over this, it would cause a conflict when rendering an unknown template could you update index.ts as well?
image

**Comment by kvyuaiss** [comment]
@Sam512 Hello????

**Comment by Sam512** [comment]
Rejected PR, please don't submit abusive pull requests.

**Pull request closed without merging**
